#!/bin/bash

: ${STANDARDS_VERSION="3.9.8"}
: ${REPO_DIR="$(pwd)/repo"}

set -e

cd "$REPO_DIR"

old_version=$(sed -n 's/^Standards-Version:\s*\(\S*\)/\1/p' debian/control)
newer=$( (echo "$STANDARDS_VERSION"; echo "$old_version") | sort -rV | head -n1)

if [ "${newer}" = "${old_version}" ]; then
    # No changes needed
    exit 0
fi

sed -i 's/^Standards-Version:.*$/Standards-Version: '"$STANDARDS_VERSION"'/' debian/control
git commit -a -m "Bump Standards-Version to $STANDARDS_VERSION"
