#!/bin/sh

: ${STANDARDS_VERSION="3.9.8"}
: ${repo_dir="$(pwd)/repo"}

set -e

cd "$repo_dir"

old_version=$(sed -n 's/^Standards-Version:\s*\(\S*\)/\1/p' debian/control)
newer=$(sort -rV <(echo "$STANDARDS_VERSION") <(echo "$old_version") | head -n1)

if [ "${newer}" = "${old_version}" ]; then
    # No changes needed
    exit 0
fi

sed -i 's/^Standards-Version:.*$/Standards-Version: '"$STANDARDS_VERSION"'/' debian/control
git commit -a -m "Bump Standards-Version to $STANDARDS_VERSION"
