#!/usr/bin/env python3
# -*- coding: utf8 -*-
# update_symbols, use pkgkde-symbolshelper to update the symbols files
#  Copyright © 2016 Maximiliano Curia <maxy@gnuservers.com.ar>

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program; if not, see <http://www.gnu.org/licenses/>.

import argparse
import glob
import logging
import os
import re
import subprocess
import sys

import requests
from lxml import html


def process_options():
    kw = {
        'format': '[%(levelname)s] %(message)s',
    }

    arg_parser = argparse.ArgumentParser(
        description='Update symbols files with the logs from the buildds.')
    arg_parser.add_argument('-d', '--package-dir', default='repo')
    arg_parser.add_argument('--debug', action='store_true')
    arg_parser.add_argument('--version',
                            default=os.environ.get('VERSION', ''))
    arg_parser.add_argument('--distribution',
                            default=os.environ.get('DISTRIBUTION', ''))
    arg_parser.add_argument('--jenkins-url',
                            default=os.environ.get('JENKINS_URL', ''))
    arg_parser.add_argument('--job-name',
                            default=os.environ.get('JOB_NAME', ''))
    arg_parser.add_argument('--no-act', action='store_true')
    arg_parser.add_argument('--aux-dir', default='build/update_symbols')
    args = arg_parser.parse_args()

    if args.debug:
        kw['level'] = logging.DEBUG

    logging.basicConfig(**kw)

    return args


def get_distribution(package_dir, distribution):
    distribution = distribution.lower()
    if distribution:
        return distribution
    cmd = ['dpkg-parsechangelog', '-S', 'distribution']
    distribution = subprocess.check_output(
        cmd, cwd=package_dir, universal_newlines=True).strip().lower()
    return distribution


def ensure_path(path):
    ''' Create path if it doesn't exists '''
    if not os.path.exists(path):
        os.makedirs(path)
    return path


def get_source_name(package_dir):
    cmd = ['dpkg-parsechangelog', '-S', 'source']
    return subprocess.check_output(
        cmd, cwd=package_dir, universal_newlines=True).strip().lower()


def get_version(package_dir, version):
    if version:
        return version
    cmd = ['dpkg-parsechangelog', '-S', 'version']
    return subprocess.check_output(
        cmd, cwd=package_dir, universal_newlines=True).strip().lower()


def symbols_files(basedir):
    return glob.glob(os.path.join(basedir, 'debian/*.symbols'))


def git_changes(workdir):
    ''' Check if there are uncommitted changes pending '''
    status = subprocess.check_output(
        ['git', 'status', '--porcelain'], cwd=workdir,
        universal_newlines=True)
    return status.strip()


def git_commit(workdir, msg):
    ''' Commit pending changes '''
    cmd = ['git', 'commit', '-a', '-m', msg]
    subprocess.call(cmd, cwd=workdir)


def git_clean(workdir):
    ''' Remove not commited files from the worktree '''
    cmd = ['git', 'clean', '-f']
    subprocess.call(cmd, cwd=workdir)


def call_symbols_helper(package_dir, version, files):
    upstream_version, debian_part = version.split('-', 2)

    cmd = ['pkgkde-symbolshelper', 'batchpatch', '-v', upstream_version]
    cmd.extend(files)
    logging.debug(cmd)
    try:
        subprocess.check_call(cmd, cwd=package_dir)
    except subprocess.CalledProcessError:
        return None


def save_file(response, filename):
    with open(filename, 'wb') as f:
        for block in response.iter_content(1024):
            f.write(block)


def use_local_logs(options):
    print('Local')

    files = []
    arches = ['amd64', 'i386', 'armhf']
    base_url = options.jenkins_url
    job_name = options.job_name
    base_job, _ = job_name.rsplit('_', 2)
    for arch in arches:
        index_url = ('{base_url}/job/{base_job}_build/arch={arch}/lastBuild/'
                     'artifact/build/'.format(
                         base_url=base_url, base_job=base_job, arch=arch))

        page = requests.get(index_url)
        tree = html.fromstring(page.content)
        regexpNS = 'http://exslt.org/regular-expressions'
        result = tree.xpath(
            '//table[@class="fileList"]'
            '//a[re:test(.,"^{base_job}_.*_{arch}\\.build$", "i")]'
            '/@href'.format(base_job=base_job, arch=arch),
            namespaces={'re': regexpNS})
        if not result:
            continue

        buildlog_url = index_url + result[0]
        response = requests.get(buildlog_url)
        filename = '{dir}/{base_job}_{arch}.build'.format(
            dir=options.aux_dir, base_job=base_job, arch=arch)
        print(filename)
        save_file(response, filename)
        fullname = os.path.abspath(filename)
        files.append(fullname)
    return files


def use_buildds_logs(package_dir, version, distribution, aux_dir):
    print('Buildds')
    source_name = get_source_name(package_dir)
    cmd = ['getbuildlog', source_name, version]
    subprocess.check_call(cmd, cwd=aux_dir)
    filename_glob = '{}_{}_*.log*'.format(source_name, version)
    downloaded_glob = os.path.join(os.getcwd(), aux_dir,
                                   filename_glob)
    downloaded_files = glob.glob(downloaded_glob)
    if not downloaded_files:
        return None
    return downloaded_files


def has_missing_symbols(package_dir):
    missing_re = re.compile(r'^\s*#(DEPRECATED|MISSING)')
    for filename in symbols_files(package_dir):
        with open(filename, 'rt') as f:
            for line in f:
                if missing_re.match(line):
                    return True
    return False


def main():
    options = process_options()

    package_dir = options.package_dir
    if not symbols_files(package_dir):
        logging.info('No symbols files, ignoring.')
        sys.exit(0)

    print(os.environ)
    aux_dir = ensure_path(options.aux_dir)
    distribution = get_distribution(package_dir, options.distribution)
    version = get_version(package_dir, options.version)
    if distribution == 'unreleased':
        msg = 'Update symbols files.'
        logfiles = use_local_logs(options)
    else:
        msg = 'Update symbols files from buildds logs ({version}).'
        logfiles = use_buildds_logs(package_dir, version, distribution, aux_dir)

    if options.no_act:
        sys.exit(0)

    if not logfiles:
        # Nothing to do
        sys.exit(0)

    call_symbols_helper(package_dir, version, logfiles)
    if has_missing_symbols(package_dir):
        sys.exit(1)

    if git_changes(package_dir):
        git_commit(package_dir, msg.format(version=version))
    # Symbols helper lefts some cruft behind
    git_clean(package_dir)


if __name__ == '__main__':
    main()
