#!/usr/bin/env python3

import argparse
import glob
import logging
import os
import subprocess
import sys

import requests
from lxml import html


def process_options():
    kw = {
        'format': '[%(levelname)s] %(message)s',
    }

    arg_parser = argparse.ArgumentParser(
        description='Update symbols files with the logs from the buildds.')
    arg_parser.add_argument('-d', '--package-dir', default='repo')
    arg_parser.add_argument('--debug', action='store_true')
    arg_parser.add_argument('--version',
                            default=os.environ.get('VERSION', ''))
    arg_parser.add_argument('--distribution',
                            default=os.environ.get('DISTRIBUTION', ''))
    arg_parser.add_argument('--jenkins-url',
                            default=os.environ.get('JENKINS_URL', ''))
    arg_parser.add_argument('--job-name',
                            default=os.environ.get('JOB_NAME', ''))
    arg_parser.add_argument('--no-act', action='store_true')
    arg_parser.add_argument('--aux-dir', default='build/update_symbols')
    args = arg_parser.parse_args()

    if args.debug:
        kw['level'] = logging.DEBUG

    logging.basicConfig(**kw)

    return args


def get_distribution(package_dir, distribution):
    distribution = distribution.lower()
    if distribution:
        return distribution
    cmd = ['dpkg-parsechangelog', '-S', 'distribution']
    distribution = subprocess.check_output(
        cmd, cwd=package_dir, universal_newlines=True).strip().lower()
    return distribution


def ensure_path(path):
    ''' Create path if it doesn't exists '''
    if not os.path.exists(path):
        os.makedirs(path)
    return path


def get_source_name(package_dir):
    cmd = ['dpkg-parsechangelog', '-S', 'source']
    return subprocess.check_output(
        cmd, cwd=package_dir, universal_newlines=True).strip().lower()


def get_version(package_dir, version):
    if version:
        return version
    cmd = ['dpkg-parsechangelog', '-S', 'version']
    return subprocess.check_output(
        cmd, cwd=package_dir, universal_newlines=True).strip().lower()


def symbols_files(basedir):
    return glob.glob(os.path.join(basedir, 'debian/*.symbols'))


def git_changes(workdir):
    ''' Check if there are uncommitted changes pending '''
    status = subprocess.check_output(
        ['git', 'status', '--porcelain'], cwd=workdir,
        universal_newlines=True)
    return status.strip()


def git_commit(workdir, msg):
    ''' Commit pending changes '''
    cmd = ['git', 'commit', '-a' '-m', msg]
    subprocess.call(cmd, cwd=workdir)


def call_symbols_helper(package_dir, version, files):
    upstream_version, debian_part = version.split('-', 2)

    cmd = ['pkgkde-symbolshelper', 'batchpatch', '-v', upstream_version]
    cmd.extend(files)
    try:
        subprocess.check_call(cmd, cwd=package_dir)
    except subprocess.CalledProcessError:
        return None


def use_local_logs(options):
    print('Local')

    arches = ['amd64', 'i386', 'armel', 'armhf']
    base_url = options.jenkins_url
    job_name = options.job_name
    base_job, _ = job_name.rsplit('_', 2)
    for arch in arches:
        index_url = ('{base_url}/job/{base_job}_build/arch={arch}/lastBuild/'
                     'artifact/build/'.format(
                         base_url=base_url, base_job=base_job, arch=arch))

        page = requests.get(index_url)
        tree = html.fromstring(page.content)
        regexpNS = 'http://exslt.org/regular-expressions'
        result = tree.xpath(
            '//table[@class="fileList"]'
            '//a[re:test(.,"^{base_job}_.*_{arch}\\.build$", "i")]'
            '/@href'.format(base_job=base_job, arch=arch),
            namespaces={'re': regexpNS})
        print(result.text)

        return


def use_buildds_logs(package_dir, version, distribution, aux_dir):
    print('Buildds')
    source_name = get_source_name(package_dir)
    cmd = ['getbuildlog', source_name, version]
    subprocess.check_call(cmd, cwd=aux_dir)
    filename_glob = '{}_{}_*.log*'.format(source_name, version)
    downloaded_glob = os.path.join(os.getcwd(), aux_dir,
                                   filename_glob)
    downloaded_files = glob.glob(downloaded_glob)
    if not downloaded_files:
        return None
    return downloaded_files


def main():
    options = process_options()

    package_dir = options.package_dir
    if not symbols_files(package_dir):
        logging.info('No symbols files, ignoring.')
        sys.exit(0)

    print(os.environ)
    aux_dir = ensure_path(options.aux_dir)
    distribution = get_distribution(package_dir, options.distribution)
    version = get_version(package_dir, options.version)
    if distribution == 'unreleased':
        msg = 'Update symbols files.'
        logfiles = use_local_logs(options)
    else:
        msg = 'Update symbols files from buildds logs ({version}).'
        logfiles = use_buildds_logs(package_dir, version, distribution, aux_dir)

    if options.no_act:
        sys.exit(0)

    if not logfiles:
        # Nothing to do
        sys.exit(0)

    call_symbols_helper(package_dir, version, logfiles)
    if git_changes(package_dir):
        git_commit(package_dir, msg.format(version=version))


if __name__ == '__main__':
    main()
