#!/usr/bin/env python3

import argparse
import glob
import logging
import os
import sys


def process_options():

    kw = {
        'format': '[%(levelname)s] %(message)s',
    }

    arg_parser = argparse.ArgumentParser(
        description='Update symbols files with the logs from the buildds.')
    arg_parser.add_argument('-d', '--package-dir', default='repo')
    arg_parser.add_argument('--debug', default=False)
    arg_parser.add_argument('--distribution',
                            default=os.environ.get('last_distribution',
                                                   'unreleased'))
    arg_parser.add_argument('--no-act', action='store_true')
    args = arg_parser.parse_args()

    if args.debug:
        kw['level'] = logging.DEBUG

    logging.basicConfig(**kw)

    return args


def symbols_files(basedir):
    return glob.glob(os.path.join(basedir, 'debian/*.symbols'))


def use_local_logs():
    print('Local')


def use_buildds_logs(distribution):
    print('Buildds')


def main():
    options = process_options()

    if not symbols_files(options.package_dir):
        logging.info('No symbols files, ignoring.')
        sys.exit(0)

    print(os.environ)
    if options.distribution.lower() == 'unreleased':
        use_local_logs()
    else:
        use_buildds_logs(options.distribution.lower())

    if options.no_act:
        sys.exit(0)


if __name__ == '__main__':
    main()
